version: '3.8'

services:
  chatbot:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - bot_data:/app/data  # Volumen persistente para datos del bot
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}  # Cargar variable de entorno desde .env

volumes:
  bot_data:  # Definir un volumen llamado bot_data