version: '3.8'

services:
  chatbot:
    build: .
    ports:
      - "3000:3000"
    shm_size: '1gb' # Aumentar el tamaño de /dev/shm
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - /dev/shm:/dev/shm
